# Generated by Django 3.2.9 on 2021-11-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211121_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
