# Generated by Django 3.2.9 on 2021-11-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adultposts', '0002_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
