# Generated by Django 3.2.9 on 2021-11-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adultposts', '0003_alter_post_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
